#define CAPS_WORD_INVERT_ON_SHIFT
#define OLED_SCROLL_TIMEOUT 2000
#define ENCODER_RESOLUTIONS_RIGHT { 4, 2 }
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINDOWS
#define MASTER_RIGHT
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#ifdef OLED_ENABLE
#   define OLED_FONT_H "keyboards/tweetydabird/lotus58/keymaps/mardorien/glcdfont.c"
#endif

#define SPLIT_TRANSACTION_IDS_USER OLED_BRIGHTNESS_SYNC
