#define CAPS_WORD_INVERT_ON_SHIFT
#define OLED_SCROLL_TIMEOUT 2000
#define ENCODER_RESOLUTIONS_RIGHT { 4, 2 }
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINDOWS
